version: "3"
services:
  my-app-mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=vacations
    command: --default-authentication-plugin=mysql_native_password
  my-app-be:
    image: my-app-be
    depends_on:
      - my-app-mysql
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=containerized
    command:
      - /bin/sh
      - -c
      - |
        echo "sleep for 10sec"
        sleep 10s
        node dist/app.js
  my-app-fe:
    image: my-app-fe
    ports:
      - 3000:3000
